server:
  port: 8080

spring:
  cloud:
      gateway:
        discovery:
          locator:
            lowerCaseServiceId: true
            enabled: true
        routes:
          # 传输模块
          - id: auth
            uri: lb://visPro-auth
            predicates:
              - Path=/auth/**
            filters:
              - StripPrefix=1 
                    # 传输模块
          - id: system
            uri: lb://visPro-system
            predicates:
              - Path=/system/**
            filters:
              - StripPrefix=1 
              
# 安全配置
security:
  # 不校验白名单
  ignore:
    whites:
      - /auth/logout
      - /auth/login
      - /auth/register
      - /*/v2/api-docs
      - /*/v3/api-docs
      - /csrf